---
- name: Generate Hosts File
  hosts: leader
  become_method: sudo
  gather_facts: true
  vars:
    nodeip: var=ansible_eth1.ipv4.address
  tasks:
    - name: Remove pre-existing kubernetes files
      shell: |
        sudo rm /etc/kubernetes/manifests/kube-apiserver.yaml
        sudo rm /etc/kubernetes/manifests/kube-controller-manager.yaml
        sudo rm /etc/kubernetes/manifests/kube-scheduler.yaml
        sudo rm /etc/kubernetes/manifests/etcd.yaml
        sudo rm -rf /var/lib/etcd

    - name: Reset the kubeadm module
      shell: |
        sudo kubeadm reset << EOF
        y
        EOF


    - name: Initializing Kubernetes cluster
      shell: kubeadm init --control-plane-endpoint cohaproxy:80 --upload-certs --apiserver-advertise-address {{ansible_default_ipv4.address}} --pod-network-cidr 192.168.0.0/16 --service-cidr 192.168.2.0/24 --v=5
      register: output
    - name: Storing Logs and Generated token for future purpose.
      local_action: copy content={{ output.stdout }} dest="./token"
    - name: Copying required files
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Install calico pod network
      command: kubectl create -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml

